_wandb:
    value:
        cli_version: 0.19.11
        m: []
        python_version: 3.12.9
        t:
            "1":
                - 1
                - 55
                - 100
            "2":
                - 1
                - 55
                - 100
            "3":
                - 13
                - 23
                - 55
            "4": 3.12.9
            "5": 0.19.11
            "8":
                - 3
                - 5
            "12": 0.19.11
            "13": windows-amd64
amp:
    value: false
batch_size:
    value: 2
epochs:
    value: 10
img_scale:
    value: 0.5
learning_rate:
    value: 0.0001
save_checkpoint:
    value: true
val_percent:
    value: 0.25
